#!/bin/sh

set -eu

exec >/dev/null

# make the working copy identical to the last commit
git add .
git stash

# do the actual sync
rsync -rz --delete --exclude '.git*' --exclude-from .gitignore \
    ./ tug.org:texdoc_html/

# get the working copy back
git stash pop
git reset --mixed HEAD
