#!/usr/bin/perl

# Basic checks (mainly that texdoc doesn't crash with various syntaxes).
#
# The script manipulates the environment to make sure the right versions and
# path are used.
#
# Manuel Pégourié-Gonnard, 2010. WTFPL v2.

my $usage = "Usage: $0 [--td=texdoc-path] [--tl=texlive_path]";

use warnings 'FATAL' => 'all';
use strict;
use utf8;
use open qw(:std utf8);
use TdTools;

my $conf = TdTools::setup($usage, 0);
my $td_path = $conf->{texdoc_path};

# various command lines and associated exit status
my %cl_exit = (
    '' => 2,
    '--version' => 0,
    '--help' => 0,
    '--foobar' => 2,
    'foobar' => 0,
    '-l -M -q texdoc' => 0,
);

# check that the command lines return the right exit code
my $texdoc = "texlua $td_path/script/texdoc.tlu";
while (my ($cl, $status) = each(%cl_exit)) {
    system("$texdoc $cl >/dev/null 2>&1");
    my $code = $? >> 8;
    die "`texdoc $cl' failed" if $code != $status;
}

__END__
