#!/usr/bin/perl

# Wrap check-aliases.tlu
#
# Manuel Pégourié-Gonnard, 2010. WTFPL v2.

my $usage = <<USAGE;
Usage: $0 [--td=texdoc-path] [--tl=texlive_path] [--dont-check--branch]
USAGE

use warnings;
use strict;
use utf8;
use open qw(:std utf8);
use TdTools;

my $conf = TdTools::setup($usage, 1);

exec "texlua $conf->{texdoc_path}/tools/check-aliases.tlu";

__END__
