#!/bin/sh

# Written in 2008 by Manuel Pégourié-Gonnard; placed under the WTFPL v2.
#
# Update texdoc from a texdoc working copy to a texlive working copy.

function usage() {
    echo "Usage: $0 [-all|-cnf|-doc] texdoc-trunk texlive-trunk" >&2
    exit 1
}

# check what to do
case $1 in
    -all)
        updoc=x 
        upcnf=x
        uptlu=x
        ;;
    -cnf)
        upcnf=x
        ;;
    -doc)
        upcnf=x
        ;;
    *)
        usage
        ;;
esac

# the location of the working copies
TEXDOC="$2"
TEXLIVE="$3"

test -d "$TEXDOC" || usage
test -d "$TEXLIVE" || usage

# various locations in the tl tree
TLTEXMF="$TEXLIVE/Master/texmf"
DOC="doc/texdoc"
MAN="doc/man/man1"
SCRIPT="scripts/texdoc"
CONF="texdoc"

# the copy itself
if [ -n "$updoc" ]; then
    # just make sure the generated doc is up-to-date first
    (cd "$TEXDOC/doc" && make )
    cp "$TEXDOC/doc/texdoc.tex" "$TEXDOC/doc/texdoc.pdf" "$TLTEXMF/$DOC" 
    cp "$TEXDOC/doc/texdoc.1" "$TLTEXMF/$MAN"
    cp "$TEXDOC/doc/texdoc.1.pdf" "$TLTEXMF/$MAN/texdoc.pdf"
fi
if [ -n "$upcnf" ]; then
    cp "$TEXDOC/texdoc.cnf" "$TLTEXMF/$CONF"
fi
if [ -n "$uptlu" ]; then
    sed -e "s/^version = '\(.\..*\)+'$/version = '\1'/" "$TEXDOC/texdoc.tlu" \
    > "$TLTEXMF/$SCRIPT/texdoc.tlu"
fi

# commit help
echo "cd $TLTEXMF && svn ci $DOC $MAN/texdoc.* $SCRIPT $CONF"
