#!/usr/bin/perl

# Manuel Pégourié-Gonnard, 2009. WTFPL v2.

use warnings 'FATAL' => 'all';
use Fatal qw(:void open close opendir closedir chdir);
use strict;
use utf8;
use open qw(:std utf8);

# Update various texdoc files from a texdoc git repo to a texlive repo.
# Use '.' or '..' as the default texdoc repo and $TLROO for texlive.
# Default set of files is 'all'.
my $usage = <<USAGE;
Usage: $0 [all|tlu|cnf|doc [...]] [--td=td-path] [--tl=tlmaster]
USAGE

# TL directories
use constant {
    'TL_scr'    => 'texmf/scripts/texdoc',
    'TL_cnf'    => 'texmf/texdoc',
    'TL_doc'    => 'texmf/doc/texdoc',
    'TL_man'    => 'texmf/doc/man/man1'
};

# file sets and destination directories
my %filesets = (
    'tlu' => {  'texdoc.tlu'            => TL_scr },
    'cnf' => {  'texdoc.cnf'            => TL_cnf },
    'doc' => {  'doc/texdoc.tex'        => TL_doc,
                'doc/texdoc.pdf'        => TL_doc,
                'doc/texdoc.1'          => TL_man,
                'doc/texdoc.man1.pdf'   => TL_man,
    });
@{$filesets{all}}{values %$_} = keys %$_ for (values %filesets);

# defaults
my $texdoc_path = -d '.git' ? '.' : -d '../.git' ? '..' : undef;
my $texlive_path = $ENV{'TLROOT'};

# get options
use Getopt::Long;
GetOptions(
    'td=s' => \$texdoc_path,
    'tl=s' => \$texlive_path,
) or die "Unkown option.\n$usage";

# chdir to source directory 
chdir($texdoc_path) or die "chdir $texdoc_path failed.\n";

# get the file set
my %files;
@ARGV = ('all') if @ARGV == 0;
for my $fs (@ARGV) {
    defined $filesets{$fs} or die "Unkown fileset $fs.\n$usage";
    @files{values %{$filesets{$fs}}} = keys %{$filesets{$fs}};
}

# rebuild documentation if needed
if (grep /doc\//, keys %files) {
    system("cd doc && make");
    die "Could not make documentation: $!.\n" if $?;
}

# do the actual copy and compute the list of touched directories
my %touched_dir;
system 'pwd';
while (my ($s, $d) = each %files) {
    $touched_dir{$d}++;
    my $dest = "$texlive_path/$d";
    -d $dest or die "No such directory: $dest.\n";
    system 'cp', '-t', $dest, $s;
    die "Could not copy $s to $dest: $!\n" if $?;
}

# print some information
print "Done. In order to commit, use:\ncd $texlive_path\nsvn ci ";
print join(' ', keys %touched_dir), "\n";
